edit_with_sublime_text = true

output_filepath = '''C:\Users\Matt\PycharmProjects\Quintessent Presentation\resources\analysis_results'''

[input_dir_paths]
    liv = '''C:\Users\Matt\PycharmProjects\Quintessent Presentation\resources\test_results\data.csv'''
    rev_iv = ''

[analysis_flags]
    plot = true
    liv.analysis = true
    liv.threshold = true
    liv.slope_efficiency = true
    liv.peak_efficiency = true
    liv.peak_power = true
    rev_iv.analysis = false
